export const siteCopy = {
  "pt-BR": {
    skip: "Pular para o conteúdo",
    nav: {
      product: "Recursos", how: "Como funciona", events: "Eventos",
      community: "Comunidade", aethron: "Aethron", integrations: "Integrações",
      beta: "Beta fechado", faq: "Perguntas frequentes", elyndor: "Elyndor",
      join: "Entrar no beta", tester: "Login de testador",
      openMenu: "Abrir menu", closeMenu: "Fechar menu", language: "Idioma",
      primary: "Navegação principal", menuTitle: "Menu",
    },
    hero: {
      eyebrow: "BETA FECHADO PARA ANDROID",
      title: "Corra no mundo real. Progrida em outro.",
      body: "MythStride transforma suas corridas em progresso de RPG. Complete missões, enfrente chefes, conquiste recompensas e construa sua jornada em Elyndor — movida pela distância que você percorre no mundo real.",
      primary: "Entrar na lista do beta", secondary: "Descobrir o MythStride",
      note: "O acesso ao beta é realizado por convite para dispositivos Android compatíveis.",
    },
    section: {
      flow: { eyebrow: "CORRIDA ENCONTRA RPG", title: "Cada quilômetro faz a sua história avançar.", body: "No MythStride, correr não termina quando a atividade é salva. Sua distância alimenta missões, progressão, batalhas e conquistas dentro de Elyndor." },
      interface: { eyebrow: "SUA JORNADA", title: "Seu progresso ganha forma.", body: "Acompanhe corridas, evolução, batalhas, equipamentos e conquistas em uma experiência criada para conectar performance real e fantasia." },
      battle: { eyebrow: "BATALHAS DE ELYNDOR", title: "Sua distância se transforma em poder.", body: "As corridas elegíveis contribuem para o dano contra chefes. Cada encontro conecta o esforço realizado no mundo real ao avanço da sua jornada em Elyndor." },
      rewards: { eyebrow: "PROGRESSÃO", title: "Construa uma jornada que é só sua.", body: "Equipamentos, itens, conquistas, ouro e relíquias registram sua evolução. Cada recompensa conquistada se torna parte da identidade do seu personagem." },
      community: { eyebrow: "AVANCE JUNTO", title: "Toda jornada pode ser pessoal. Nenhuma precisa ser solitária.", body: "Conecte-se com outros jogadores, acompanhe rankings, participe de grupos e compartilhe conquistas dentro do universo MythStride." },
      aethron: { eyebrow: "GUARDIÃO DA CHAMA", title: "Aethron transforma progresso em narrativa.", body: "Aethron é o companheiro narrativo do MythStride. Ele utiliza contexto da sua jornada para conectar corridas, progresso e acontecimentos de Elyndor em uma experiência mais pessoal." },
      integrations: { eyebrow: "CORRA DO SEU JEITO", title: "Do celular ao pulso.", body: "MythStride foi criado para acompanhar a corrida onde ela acontece. No Android, a experiência conecta registro de atividade, progressão e o universo de Elyndor." },
      privacy: { eyebrow: "SEUS DADOS. SEU CONTROLE.", title: "Privacidade faz parte da experiência.", body: "MythStride utiliza dados necessários para operar sua conta, registrar atividades, proteger a integridade do jogo e oferecer os recursos que você escolhe utilizar." },
      beta: { eyebrow: "BETA FECHADO", title: "Seja um dos primeiros Striders.", body: "O MythStride está em beta fechado para Android. Os participantes desta fase estarão entre os primeiros jogadores a explorar Elyndor e colocar a experiência à prova." },
      lore: { eyebrow: "CRÔNICAS DE ELYNDOR", title: "Aethron despertou quando a Chama quase se apagou.", body: "Elyndor não caiu em uma única guerra. Sob a Névoa, propósito e memória começaram a desaparecer. Cada Strider que retorna ao caminho fortalece a resistência e mantém a Chama acesa." },
      faq: { eyebrow: "MYTHSTRIDE", title: "Perguntas frequentes", body: "Tudo o que você precisa saber sobre o MythStride e o beta fechado." },
      waitlist: { eyebrow: "ENTRE PARA A PRIMEIRA GERAÇÃO", title: "Sua jornada pode começar aqui.", body: "Entre na lista do beta fechado e tenha a oportunidade de explorar Elyndor entre os primeiros jogadores do MythStride." },
    },
    waitlist: {
      name: "Nome (opcional)", email: "Email", submit: "Entrar na lista do beta", loading: "Enviando...",
      disclosure: "Usaremos seu email e as informações técnicas necessárias para administrar a lista, prevenir abuso e entrar em contato sobre o beta. Ao se cadastrar, você confirma ter 18 anos ou mais.",
      ageConfirmation: "Declaro ter 18 anos ou mais.", ageRequired: "Confirme que você tem 18 anos ou mais.",
      capacity: "O cadastro na lista não garante convite imediato. As vagas são liberadas de acordo com a capacidade do beta e a compatibilidade do dispositivo.",
      privacyLink: "Consulte nossa Política de Privacidade",
      success: "Você está na lista. Avisaremos por email quando houver uma oportunidade de participar do beta.",
      duplicate: "Este email já está na lista do beta.", invalid: "Informe um email válido.",
      failure: "Não foi possível acessar a lista agora. Tente novamente.", honeypot: "Não preencha este campo",
    },
    footer: { product: "Produto", universe: "Universo", support: "Suporte", legal: "Legal", language: "Idioma", social: "Social", rights: "Todos os direitos reservados." },
    accountDeletion: {
      formTitle: "Solicitar exclusão de conta", formIntro: "Informe o email da conta. Se existir uma conta associada, enviaremos um link de verificação.",
      emailLabel: "Email da conta", submit: "Solicitar exclusão", loading: "Enviando...", honeypot: "Não preencha este campo",
      requested: "Caso exista uma conta associada a esse email, enviaremos as próximas instruções.", invalidEmail: "Informe um email válido.",
      rateLimited: "Muitas tentativas. Aguarde alguns minutos e tente novamente.", unavailable: "Não foi possível processar a solicitação agora. Tente novamente mais tarde.",
      confirmChecking: "Verificando o link de confirmação...", confirmMissingToken: "Este link de confirmação está incompleto. Solicite um novo link de exclusão.",
      confirmScheduled: "Verificação concluída. Sua solicitação de exclusão foi confirmada e será processada de acordo com nossa Política de Privacidade.", confirmAwaitingRetention: "Verificação concluída. Sua solicitação de exclusão foi confirmada e será processada de acordo com nossa Política de Privacidade.",
      confirmGenericSuccess: "Verificação concluída. Sua solicitação de exclusão foi confirmada.", confirmInvalid: "Este link é inválido ou já expirou. Solicite um novo link de exclusão.",
      confirmRateLimited: "Muitas tentativas. Aguarde alguns minutos e tente novamente.", confirmUnavailable: "Não foi possível confirmar agora. Tente novamente mais tarde.",
      backToRequest: "Solicitar novo link",
    },
  },
  en: {
    skip: "Skip to content",
    nav: {
      product: "Features", how: "How it works", events: "Events", community: "Community", aethron: "Aethron",
      integrations: "Integrations", beta: "Closed beta", faq: "FAQ", elyndor: "Elyndor",
      join: "Join the beta", tester: "Beta tester login",
      openMenu: "Open menu", closeMenu: "Close menu", language: "Language",
      primary: "Main navigation", menuTitle: "Menu",
    },
    hero: {
      eyebrow: "ANDROID CLOSED BETA", title: "Run in the real world. Progress in another.",
      body: "MythStride turns your runs into RPG progression. Complete quests, face bosses, earn rewards, and build your journey through Elyndor — powered by the distance you cover in the real world.",
      primary: "Join the beta list", secondary: "Discover MythStride", note: "Beta access is invite-only for compatible Android devices.",
    },
    section: {
      flow: { eyebrow: "RUNNING MEETS RPG", title: "Every kilometer moves your story forward.", body: "In MythStride, a run does not end when the activity is saved. Your distance fuels quests, progression, battles, and achievements across Elyndor." },
      interface: { eyebrow: "YOUR JOURNEY", title: "Your progress takes shape.", body: "Follow your runs, growth, battles, equipment, and achievements in an experience designed to connect real performance with fantasy." },
      battle: { eyebrow: "BATTLES OF ELYNDOR", title: "Your distance becomes power.", body: "Eligible runs contribute damage against bosses. Each encounter connects real-world effort to the progress of your journey through Elyndor." },
      rewards: { eyebrow: "PROGRESSION", title: "Build a journey that is yours alone.", body: "Equipment, items, achievements, gold, and relics record your growth. Every reward becomes part of your character's identity." },
      community: { eyebrow: "MOVE FORWARD TOGETHER", title: "Every journey can be personal. None has to be lonely.", body: "Connect with other players, follow rankings, join groups, and share achievements across the MythStride universe." },
      aethron: { eyebrow: "KEEPER OF THE FLAME", title: "Aethron turns progress into narrative.", body: "Aethron is MythStride's narrative companion. It uses context from your journey to connect runs, progress, and events in Elyndor through a more personal experience." },
      integrations: { eyebrow: "RUN YOUR WAY", title: "From phone to wrist.", body: "MythStride is designed to follow the run where it happens. On Android, the experience connects activity tracking, progression, and the world of Elyndor." },
      privacy: { eyebrow: "YOUR DATA. YOUR CONTROL.", title: "Privacy is part of the experience.", body: "MythStride uses the data needed to operate your account, record activities, protect game integrity, and provide the features you choose to use." },
      beta: { eyebrow: "CLOSED BETA", title: "Become one of the first Striders.", body: "MythStride is in closed beta for Android. Participants in this phase will be among the first players to explore Elyndor and put the experience to the test." },
      lore: { eyebrow: "CHRONICLES OF ELYNDOR", title: "Aethron awoke when the Flame nearly went out.", body: "Elyndor did not fall in a single war. Beneath the Mist, purpose and memory began to fade. Every Strider who returns to the path strengthens the resistance and keeps the Flame alive." },
      faq: { eyebrow: "MYTHSTRIDE", title: "Frequently asked questions", body: "Everything you need to know about MythStride and the closed beta." },
      waitlist: { eyebrow: "JOIN THE FIRST GENERATION", title: "Your journey can begin here.", body: "Join the closed beta list for a chance to explore Elyndor among MythStride's first players." },
    },
    waitlist: {
      name: "Name (optional)", email: "Email", submit: "Join the beta list", loading: "Sending...",
      disclosure: "We will use your email and the technical information needed to manage the list, prevent abuse, and contact you about the beta. By signing up, you confirm that you are 18 or older.",
      ageConfirmation: "I confirm that I am 18 years of age or older.", ageRequired: "Confirm that you are 18 years of age or older.",
      capacity: "Joining the list does not guarantee an immediate invitation. Places are released according to beta capacity and device compatibility.",
      privacyLink: "Read our Privacy Policy", success: "You are on the list. We will email you when there is an opportunity to join the beta.",
      duplicate: "This email is already on the beta list.", invalid: "Enter a valid email address.", failure: "The list is unavailable right now. Please try again.", honeypot: "Leave this field empty",
    },
    footer: { product: "Product", universe: "Universe", support: "Support", legal: "Legal", language: "Language", social: "Social", rights: "All rights reserved." },
    accountDeletion: {
      formTitle: "Request account deletion", formIntro: "Enter the email linked to your account. If an account is associated with it, we will send a verification link.",
      emailLabel: "Account email", submit: "Request deletion", loading: "Sending...", honeypot: "Leave this field empty",
      requested: "If an account is associated with this email, we will send the next instructions.", invalidEmail: "Enter a valid email address.",
      rateLimited: "Too many attempts. Wait a few minutes and try again.", unavailable: "We could not process your request. Please try again later.",
      confirmChecking: "Verifying the confirmation link...", confirmMissingToken: "This confirmation link is incomplete. Request a new deletion link.",
      confirmScheduled: "Verification complete. Your deletion request has been confirmed and will be processed in accordance with our Privacy Policy.", confirmAwaitingRetention: "Verification complete. Your deletion request has been confirmed and will be processed in accordance with our Privacy Policy.",
      confirmGenericSuccess: "Verification complete. Your deletion request has been confirmed.", confirmInvalid: "This link is invalid or has expired. Request a new deletion link.",
      confirmRateLimited: "Too many attempts. Wait a few minutes and try again.", confirmUnavailable: "We could not confirm the request. Please try again later.", backToRequest: "Request a new link",
    },
  },
  es: {
    skip: "Saltar al contenido",
    nav: {
      product: "Funciones", how: "Cómo funciona", events: "Eventos", community: "Comunidad", aethron: "Aethron",
      integrations: "Integraciones", beta: "Beta cerrada", faq: "Preguntas frecuentes", elyndor: "Elyndor",
      join: "Unirme a la beta", tester: "Acceso para participantes",
      openMenu: "Abrir menú", closeMenu: "Cerrar menú", language: "Idioma",
      primary: "Navegación principal", menuTitle: "Menú",
    },
    hero: {
      eyebrow: "BETA CERRADA PARA ANDROID", title: "Corre en el mundo real. Progresa en otro.",
      body: "MythStride convierte tus carreras en progreso de RPG. Completa misiones, enfréntate a jefes, consigue recompensas y construye tu viaje por Elyndor, impulsado por la distancia que recorres en el mundo real.",
      primary: "Unirme a la lista de la beta", secondary: "Descubrir MythStride", note: "El acceso a la beta se realiza por invitación para dispositivos Android compatibles.",
    },
    section: {
      flow: { eyebrow: "CARRERA Y RPG", title: "Cada kilómetro hace avanzar tu historia.", body: "En MythStride, la carrera no termina al guardar la actividad. Tu distancia impulsa misiones, progreso, batallas y logros dentro de Elyndor." },
      interface: { eyebrow: "TU VIAJE", title: "Tu progreso cobra forma.", body: "Sigue tus carreras, evolución, batallas, equipo y logros en una experiencia creada para conectar rendimiento real y fantasía." },
      battle: { eyebrow: "BATALLAS DE ELYNDOR", title: "Tu distancia se convierte en poder.", body: "Las carreras elegibles contribuyen al daño contra jefes. Cada encuentro conecta el esfuerzo del mundo real con el avance de tu viaje por Elyndor." },
      rewards: { eyebrow: "PROGRESO", title: "Construye un viaje que sea solo tuyo.", body: "El equipo, los objetos, los logros, el oro y las reliquias registran tu evolución. Cada recompensa se convierte en parte de la identidad de tu personaje." },
      community: { eyebrow: "AVANCEN JUNTOS", title: "Cada viaje puede ser personal. Ninguno tiene que ser solitario.", body: "Conecta con otros jugadores, sigue las clasificaciones, participa en grupos y comparte logros dentro del universo MythStride." },
      aethron: { eyebrow: "GUARDIÁN DE LA LLAMA", title: "Aethron convierte el progreso en narrativa.", body: "Aethron es el compañero narrativo de MythStride. Utiliza el contexto de tu viaje para conectar carreras, progreso y acontecimientos de Elyndor en una experiencia más personal." },
      integrations: { eyebrow: "CORRE A TU MANERA", title: "Del móvil a la muñeca.", body: "MythStride fue creado para acompañar la carrera donde sucede. En Android, la experiencia conecta el registro de actividad, el progreso y el mundo de Elyndor." },
      privacy: { eyebrow: "TUS DATOS. TU CONTROL.", title: "La privacidad forma parte de la experiencia.", body: "MythStride utiliza los datos necesarios para operar tu cuenta, registrar actividades, proteger la integridad del juego y ofrecer las funciones que eliges utilizar." },
      beta: { eyebrow: "BETA CERRADA", title: "Conviértete en uno de los primeros Striders.", body: "MythStride está en beta cerrada para Android. Los participantes de esta fase estarán entre los primeros jugadores en explorar Elyndor y poner a prueba la experiencia." },
      lore: { eyebrow: "CRÓNICAS DE ELYNDOR", title: "Aethron despertó cuando la Llama casi se apagó.", body: "Elyndor no cayó en una sola guerra. Bajo la Niebla, el propósito y la memoria comenzaron a desaparecer. Cada Strider que regresa al camino fortalece la resistencia y mantiene viva la Llama." },
      faq: { eyebrow: "MYTHSTRIDE", title: "Preguntas frecuentes", body: "Todo lo que necesitas saber sobre MythStride y la beta cerrada." },
      waitlist: { eyebrow: "ÚNETE A LA PRIMERA GENERACIÓN", title: "Tu viaje puede comenzar aquí.", body: "Únete a la lista de la beta cerrada y ten la oportunidad de explorar Elyndor entre los primeros jugadores de MythStride." },
    },
    waitlist: {
      name: "Nombre (opcional)", email: "Email", submit: "Unirme a la lista de la beta", loading: "Enviando...",
      disclosure: "Usaremos tu email y la información técnica necesaria para administrar la lista, prevenir abusos y contactarte sobre la beta. Al registrarte, confirmas que tienes 18 años o más.",
      ageConfirmation: "Declaro que tengo 18 años o más.", ageRequired: "Confirma que tienes 18 años o más.",
      capacity: "Registrarte no garantiza una invitación inmediata. Las plazas se liberan según la capacidad de la beta y la compatibilidad del dispositivo.",
      privacyLink: "Consulta nuestra Política de Privacidad", success: "Ya estás en la lista. Te avisaremos por email cuando haya una oportunidad de participar en la beta.",
      duplicate: "Este email ya está en la lista de la beta.", invalid: "Introduce un email válido.", failure: "No se pudo acceder a la lista. Inténtalo de nuevo.", honeypot: "Deja este campo vacío",
    },
    footer: { product: "Producto", universe: "Universo", support: "Soporte", legal: "Legal", language: "Idioma", social: "Social", rights: "Todos los derechos reservados." },
    accountDeletion: {
      formTitle: "Solicitar la eliminación de la cuenta", formIntro: "Introduce el email asociado a tu cuenta. Si existe una cuenta vinculada, enviaremos un enlace de verificación.",
      emailLabel: "Email de la cuenta", submit: "Solicitar eliminación", loading: "Enviando...", honeypot: "Deja este campo vacío",
      requested: "Si existe una cuenta asociada a este email, enviaremos las próximas instrucciones.", invalidEmail: "Introduce un email válido.",
      rateLimited: "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.", unavailable: "No pudimos procesar la solicitud. Inténtalo de nuevo más tarde.",
      confirmChecking: "Verificando el enlace de confirmación...", confirmMissingToken: "Este enlace de confirmación está incompleto. Solicita un nuevo enlace de eliminación.",
      confirmScheduled: "Verificación completada. Tu solicitud de eliminación ha sido confirmada y se procesará de acuerdo con nuestra Política de Privacidad.", confirmAwaitingRetention: "Verificación completada. Tu solicitud de eliminación ha sido confirmada y se procesará de acuerdo con nuestra Política de Privacidad.",
      confirmGenericSuccess: "Verificación completada. Tu solicitud de eliminación ha sido confirmada.", confirmInvalid: "Este enlace no es válido o ha caducado. Solicita uno nuevo.",
      confirmRateLimited: "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.", confirmUnavailable: "No pudimos confirmar la solicitud. Inténtalo de nuevo más tarde.", backToRequest: "Solicitar un nuevo enlace",
    },
  },
} as const;
